// 500 題中翻英練習題庫 v2
// 新增：CEFR 分級 (A2 / B1 / B2)
// - A2: 生存英文，最基礎必備（約 165 題）
// - B1: 日常表達，能完整陳述想法（約 170 題）
// - B2: 流暢溝通，能處理複雜情境（約 165 題）
//
// 欄位：id, zh, topic, level_cefr, context
// 難度 level 欄位保留向下相容但不再使用

export const QUESTIONS = [
  // ============================================================
  // 📂 日常生活 daily (100 題)
  // ============================================================

  // ── A2 日常（35 題） ──
  { id: 1, zh: "我想要一杯咖啡", topic: "daily", level_cefr: "A2", context: "在咖啡店點餐" },
  { id: 2, zh: "請問廁所在哪裡", topic: "daily", level_cefr: "A2", context: "餐廳、機場" },
  { id: 3, zh: "可以幫我一個忙嗎", topic: "daily", level_cefr: "A2", context: "請求協助" },
  { id: 4, zh: "今天天氣真好", topic: "daily", level_cefr: "A2", context: "閒聊開場" },
  { id: 5, zh: "等我一下,我馬上回來", topic: "daily", level_cefr: "A2", context: "暫離現場" },
  { id: 6, zh: "我肚子餓了", topic: "daily", level_cefr: "A2", context: "想去吃飯" },
  { id: 7, zh: "我累了,想回家休息", topic: "daily", level_cefr: "A2", context: "跟朋友告別" },
  { id: 8, zh: "這個多少錢", topic: "daily", level_cefr: "A2", context: "購物" },
  { id: 9, zh: "我沒聽清楚,可以再說一次嗎", topic: "daily", level_cefr: "A2", context: "請求重述" },
  { id: 10, zh: "對不起,我遲到了", topic: "daily", level_cefr: "A2", context: "道歉" },
  { id: 11, zh: "你今天看起來不錯", topic: "daily", level_cefr: "A2", context: "稱讚朋友" },
  { id: 12, zh: "我也這麼覺得", topic: "daily", level_cefr: "A2", context: "同意對方" },
  { id: 13, zh: "我現在有點忙", topic: "daily", level_cefr: "A2", context: "婉拒" },
  { id: 14, zh: "你明天有空嗎", topic: "daily", level_cefr: "A2", context: "邀約" },
  { id: 15, zh: "我不太確定", topic: "daily", level_cefr: "A2", context: "回答不確定的事" },
  { id: 16, zh: "這家店我常來", topic: "daily", level_cefr: "A2", context: "介紹常去的地方" },
  { id: 17, zh: "今天超熱的", topic: "daily", level_cefr: "A2", context: "抱怨天氣" },
  { id: 18, zh: "我最近感冒了", topic: "daily", level_cefr: "A2", context: "身體不適" },
  { id: 19, zh: "我忘記帶錢包了", topic: "daily", level_cefr: "A2", context: "尷尬情境" },
  { id: 20, zh: "幫我拿一下那個", topic: "daily", level_cefr: "A2", context: "請對方遞東西" },
  { id: 21, zh: "我不餓,謝謝", topic: "daily", level_cefr: "A2", context: "婉拒食物" },
  { id: 22, zh: "可以借我一下嗎", topic: "daily", level_cefr: "A2", context: "借東西" },
  { id: 23, zh: "我喜歡吃辣", topic: "daily", level_cefr: "A2", context: "討論口味" },
  { id: 24, zh: "你幾點要出門", topic: "daily", level_cefr: "A2", context: "確認時間" },
  { id: 25, zh: "我明天早上有事", topic: "daily", level_cefr: "A2", context: "說明行程" },
  { id: 26, zh: "我要去超市買東西", topic: "daily", level_cefr: "A2", context: "說明去向" },
  { id: 27, zh: "我昨天很晚才睡", topic: "daily", level_cefr: "A2", context: "解釋為什麼累" },
  { id: 28, zh: "這個看起來很好吃", topic: "daily", level_cefr: "A2", context: "看到食物" },
  { id: 29, zh: "我不會用這個", topic: "daily", level_cefr: "A2", context: "遇到不熟的工具" },
  { id: 30, zh: "你知道怎麼去那裡嗎", topic: "daily", level_cefr: "A2", context: "問路" },
  { id: 31, zh: "我今天心情不好", topic: "daily", level_cefr: "A2", context: "表達情緒" },
  { id: 32, zh: "我還在想", topic: "daily", level_cefr: "A2", context: "需要思考時間" },
  { id: 33, zh: "這裡禁止吸菸", topic: "daily", level_cefr: "A2", context: "提醒規則" },
  { id: 34, zh: "我下週要去日本", topic: "daily", level_cefr: "A2", context: "講旅行計畫" },
  { id: 35, zh: "我有兩個姐姐", topic: "daily", level_cefr: "A2", context: "介紹家人" },

  // ── B1 日常（35 題） ──
  { id: 36, zh: "我本來想去的,但臨時有事", topic: "daily", level_cefr: "B1", context: "朋友問為什麼沒去" },
  { id: 37, zh: "隨便你啦,你決定就好", topic: "daily", level_cefr: "B1", context: "選餐廳" },
  { id: 38, zh: "我嘴破了,吃東西很痛", topic: "daily", level_cefr: "B1", context: "解釋不想吃辣" },
  { id: 39, zh: "這個我沒什麼概念耶", topic: "daily", level_cefr: "B1", context: "不熟的話題" },
  { id: 40, zh: "你有空的時候再回我就好", topic: "daily", level_cefr: "B1", context: "傳訊息給忙的朋友" },
  { id: 41, zh: "那天我剛好有事,不好意思", topic: "daily", level_cefr: "B1", context: "拒絕邀約" },
  { id: 42, zh: "這家店 CP 值很高", topic: "daily", level_cefr: "B1", context: "推薦餐廳" },
  { id: 43, zh: "我完全忘記這件事了", topic: "daily", level_cefr: "B1", context: "想起忘了約定" },
  { id: 44, zh: "我剛剛講到哪裡了", topic: "daily", level_cefr: "B1", context: "被打斷後繼續" },
  { id: 45, zh: "那就這樣說定囉", topic: "daily", level_cefr: "B1", context: "敲定計畫" },
  { id: 46, zh: "我先走了,你們慢慢聊", topic: "daily", level_cefr: "B1", context: "先離開聚會" },
  { id: 47, zh: "我等一下要去辦點事", topic: "daily", level_cefr: "B1", context: "解釋要離開" },
  { id: 48, zh: "我覺得我快感冒了", topic: "daily", level_cefr: "B1", context: "身體不舒服" },
  { id: 49, zh: "你看起來很累的樣子", topic: "daily", level_cefr: "B1", context: "關心朋友" },
  { id: 50, zh: "我最近都沒睡好", topic: "daily", level_cefr: "B1", context: "解釋狀態不好" },
  { id: 51, zh: "今天熱到我快受不了了", topic: "daily", level_cefr: "B1", context: "抱怨天氣" },
  { id: 52, zh: "我剛剛沒聽清楚,可以再說一次嗎", topic: "daily", level_cefr: "B1", context: "沒聽到對方說的" },
  { id: 53, zh: "不好意思,打擾一下", topic: "daily", level_cefr: "B1", context: "請教陌生人" },
  { id: 54, zh: "我最近在減肥", topic: "daily", level_cefr: "B1", context: "解釋飲食習慣" },
  { id: 55, zh: "我沒什麼胃口", topic: "daily", level_cefr: "B1", context: "不想吃東西" },
  { id: 56, zh: "這件事我有印象", topic: "daily", level_cefr: "B1", context: "回憶起某事" },
  { id: 57, zh: "時間過得真快", topic: "daily", level_cefr: "B1", context: "感嘆時間" },
  { id: 58, zh: "我昨晚熬夜趕工", topic: "daily", level_cefr: "B1", context: "解釋疲累原因" },
  { id: 59, zh: "這不是我的風格", topic: "daily", level_cefr: "B1", context: "婉拒穿搭建議" },
  { id: 60, zh: "我不太會打扮", topic: "daily", level_cefr: "B1", context: "自謙" },
  { id: 61, zh: "這讓我想起以前", topic: "daily", level_cefr: "B1", context: "觸景生情" },
  { id: 62, zh: "我從來沒想過", topic: "daily", level_cefr: "B1", context: "被問到沒考慮過的事" },
  { id: 63, zh: "我一直很想去那裡", topic: "daily", level_cefr: "B1", context: "聊夢想景點" },
  { id: 64, zh: "你要小心喔", topic: "daily", level_cefr: "B1", context: "提醒對方" },
  { id: 65, zh: "這個味道我受不了", topic: "daily", level_cefr: "B1", context: "不喜歡的食物" },
  { id: 66, zh: "我有點被嚇到", topic: "daily", level_cefr: "B1", context: "意外驚訝" },
  { id: 67, zh: "我不太習慣這種食物", topic: "daily", level_cefr: "B1", context: "面對陌生料理" },
  { id: 68, zh: "我完全沒注意到", topic: "daily", level_cefr: "B1", context: "被指出漏看細節" },
  { id: 69, zh: "這個我第一次聽到", topic: "daily", level_cefr: "B1", context: "陌生資訊" },
  { id: 70, zh: "你在忙嗎", topic: "daily", level_cefr: "B1", context: "打擾前確認" },

  // ── B2 日常（30 題） ──
  { id: 71, zh: "我一直拖著沒去做", topic: "daily", level_cefr: "B2", context: "承認拖延" },
  { id: 72, zh: "這件事一直卡在我心裡", topic: "daily", level_cefr: "B2", context: "有心事" },
  { id: 73, zh: "我想了很久才決定", topic: "daily", level_cefr: "B2", context: "說明過程" },
  { id: 74, zh: "我盡量配合你的時間", topic: "daily", level_cefr: "B2", context: "約時間" },
  { id: 75, zh: "這要看情況而定", topic: "daily", level_cefr: "B2", context: "回答不確定的事" },
  { id: 76, zh: "我最近工作家庭兩頭燒", topic: "daily", level_cefr: "B2", context: "抱怨生活" },
  { id: 77, zh: "這件事我想了很多", topic: "daily", level_cefr: "B2", context: "深思熟慮" },
  { id: 78, zh: "說來話長", topic: "daily", level_cefr: "B2", context: "開啟冗長話題" },
  { id: 79, zh: "這其實沒那麼簡單", topic: "daily", level_cefr: "B2", context: "反駁過度簡化的說法" },
  { id: 80, zh: "我得先衡量一下利弊", topic: "daily", level_cefr: "B2", context: "面對選擇" },
  { id: 81, zh: "這就是現實啊", topic: "daily", level_cefr: "B2", context: "接受無奈" },
  { id: 82, zh: "我已經盡力了", topic: "daily", level_cefr: "B2", context: "表達已努力" },
  { id: 83, zh: "我需要一些時間想清楚", topic: "daily", level_cefr: "B2", context: "請求空間" },
  { id: 84, zh: "這不是三言兩語可以解釋的", topic: "daily", level_cefr: "B2", context: "複雜話題" },
  { id: 85, zh: "我並不是刻意要這樣", topic: "daily", level_cefr: "B2", context: "為自己辯解" },
  { id: 86, zh: "我覺得我快撐不下去了", topic: "daily", level_cefr: "B2", context: "壓力大時" },
  { id: 87, zh: "我從不同角度想了一下", topic: "daily", level_cefr: "B2", context: "多面思考" },
  { id: 88, zh: "我試著理解你的立場", topic: "daily", level_cefr: "B2", context: "同理對話" },
  { id: 89, zh: "事情沒有我想的那麼順利", topic: "daily", level_cefr: "B2", context: "分享挫折" },
  { id: 90, zh: "我的個性就是這樣", topic: "daily", level_cefr: "B2", context: "解釋性格" },
  { id: 91, zh: "我其實一直有在想這件事", topic: "daily", level_cefr: "B2", context: "深藏念頭" },
  { id: 92, zh: "這大概是我能做到的極限了", topic: "daily", level_cefr: "B2", context: "承認能力上限" },
  { id: 93, zh: "我一時之間不知道該怎麼反應", topic: "daily", level_cefr: "B2", context: "被突發狀況嚇到" },
  { id: 94, zh: "我只是不想讓你擔心", topic: "daily", level_cefr: "B2", context: "解釋隱瞞原因" },
  { id: 95, zh: "這讓我重新思考人生", topic: "daily", level_cefr: "B2", context: "深刻體會" },
  { id: 96, zh: "我試著慢慢調整回來", topic: "daily", level_cefr: "B2", context: "恢復中" },
  { id: 97, zh: "我不想把話講得太死", topic: "daily", level_cefr: "B2", context: "保留彈性" },
  { id: 98, zh: "我得承認,我低估了這件事", topic: "daily", level_cefr: "B2", context: "承認誤判" },
  { id: 99, zh: "我不想因為這種小事翻臉", topic: "daily", level_cefr: "B2", context: "避免衝突" },
  { id: 100, zh: "我不想再提這件事了", topic: "daily", level_cefr: "B2", context: "結束話題" },

  // ============================================================
  // 📂 工作職場 work (100 題)
  // ============================================================

  // ── A2 職場（30 題） ──
  { id: 101, zh: "我是新來的", topic: "work", level_cefr: "A2", context: "自我介紹" },
  { id: 102, zh: "我的工作是工程師", topic: "work", level_cefr: "A2", context: "介紹職業" },
  { id: 103, zh: "我在這裡工作三年了", topic: "work", level_cefr: "A2", context: "自我介紹" },
  { id: 104, zh: "我今天要請假", topic: "work", level_cefr: "A2", context: "請假" },
  { id: 105, zh: "抱歉,我遲到了", topic: "work", level_cefr: "A2", context: "道歉" },
  { id: 106, zh: "我不太懂,可以再解釋一次嗎", topic: "work", level_cefr: "A2", context: "會議中" },
  { id: 107, zh: "會議是幾點開始", topic: "work", level_cefr: "A2", context: "確認時間" },
  { id: 108, zh: "我需要幫助", topic: "work", level_cefr: "A2", context: "求助" },
  { id: 109, zh: "這個我做完了", topic: "work", level_cefr: "A2", context: "回報進度" },
  { id: 110, zh: "我先去吃午餐", topic: "work", level_cefr: "A2", context: "午休" },
  { id: 111, zh: "我同意你的看法", topic: "work", level_cefr: "A2", context: "會議表態" },
  { id: 112, zh: "我不同意", topic: "work", level_cefr: "A2", context: "反對意見" },
  { id: 113, zh: "這個檔案給你", topic: "work", level_cefr: "A2", context: "交接文件" },
  { id: 114, zh: "我在開會", topic: "work", level_cefr: "A2", context: "回覆忙碌狀態" },
  { id: 115, zh: "等一下再說", topic: "work", level_cefr: "A2", context: "延後討論" },
  { id: 116, zh: "電話來了", topic: "work", level_cefr: "A2", context: "接電話" },
  { id: 117, zh: "他不在位子上", topic: "work", level_cefr: "A2", context: "代接電話" },
  { id: 118, zh: "你可以留言給他", topic: "work", level_cefr: "A2", context: "代接電話" },
  { id: 119, zh: "我現在沒空", topic: "work", level_cefr: "A2", context: "婉拒同事" },
  { id: 120, zh: "我下週休假", topic: "work", level_cefr: "A2", context: "告知休假" },
  { id: 121, zh: "謝謝你的幫忙", topic: "work", level_cefr: "A2", context: "感謝" },
  { id: 122, zh: "沒問題,交給我", topic: "work", level_cefr: "A2", context: "接下任務" },
  { id: 123, zh: "我明天會寄給你", topic: "work", level_cefr: "A2", context: "承諾時程" },
  { id: 124, zh: "可以幫我印這個嗎", topic: "work", level_cefr: "A2", context: "請託" },
  { id: 125, zh: "影印機壞了", topic: "work", level_cefr: "A2", context: "回報設備問題" },
  { id: 126, zh: "你有收到我的信嗎", topic: "work", level_cefr: "A2", context: "追信件" },
  { id: 127, zh: "我用電腦傳給你", topic: "work", level_cefr: "A2", context: "電子檔" },
  { id: 128, zh: "我下班了", topic: "work", level_cefr: "A2", context: "打卡下班" },
  { id: 129, zh: "我明天見", topic: "work", level_cefr: "A2", context: "告別" },
  { id: 130, zh: "加油!", topic: "work", level_cefr: "A2", context: "鼓勵同事" },

  // ── B1 職場（40 題） ──
  { id: 131, zh: "這件事我晚點再處理", topic: "work", level_cefr: "B1", context: "同事問進度" },
  { id: 132, zh: "我先跟你確認一下", topic: "work", level_cefr: "B1", context: "email 開頭" },
  { id: 133, zh: "這個我需要再想想", topic: "work", level_cefr: "B1", context: "被問意見" },
  { id: 134, zh: "我可能沒辦法趕上 deadline", topic: "work", level_cefr: "B1", context: "告知延遲" },
  { id: 135, zh: "麻煩你幫我把這個轉給他", topic: "work", level_cefr: "B1", context: "請同事轉達" },
  { id: 136, zh: "我這週真的很忙,走不開", topic: "work", level_cefr: "B1", context: "婉拒" },
  { id: 137, zh: "抱歉讓你久等了", topic: "work", level_cefr: "B1", context: "晚回信" },
  { id: 138, zh: "我需要更多時間來做這個", topic: "work", level_cefr: "B1", context: "要求延期" },
  { id: 139, zh: "我完全同意你的看法", topic: "work", level_cefr: "B1", context: "強烈支持" },
  { id: 140, zh: "下週的會議改時間了", topic: "work", level_cefr: "B1", context: "通知變更" },
  { id: 141, zh: "我先把這個做完再走", topic: "work", level_cefr: "B1", context: "加班" },
  { id: 142, zh: "我需要跟主管確認一下", topic: "work", level_cefr: "B1", context: "無法立即決定" },
  { id: 143, zh: "我大致了解了", topic: "work", level_cefr: "B1", context: "收到說明後" },
  { id: 144, zh: "這不是我的錯", topic: "work", level_cefr: "B1", context: "釐清責任" },
  { id: 145, zh: "我會再追蹤一下", topic: "work", level_cefr: "B1", context: "承諾後續" },
  { id: 146, zh: "這個工作量太大了", topic: "work", level_cefr: "B1", context: "反映工作量" },
  { id: 147, zh: "我手上還有別的事", topic: "work", level_cefr: "B1", context: "無法接新任務" },
  { id: 148, zh: "這件事要跟法務討論", topic: "work", level_cefr: "B1", context: "跨部門" },
  { id: 149, zh: "我來負責這個部分", topic: "work", level_cefr: "B1", context: "主動承擔" },
  { id: 150, zh: "這部分我不太熟", topic: "work", level_cefr: "B1", context: "坦承不足" },
  { id: 151, zh: "我需要更多資訊才能判斷", topic: "work", level_cefr: "B1", context: "延後決定" },
  { id: 152, zh: "這個想法很棒", topic: "work", level_cefr: "B1", context: "肯定同事提案" },
  { id: 153, zh: "我會盡快給你回覆", topic: "work", level_cefr: "B1", context: "承諾回覆" },
  { id: 154, zh: "這對我們團隊很重要", topic: "work", level_cefr: "B1", context: "強調優先" },
  { id: 155, zh: "我會注意這一點", topic: "work", level_cefr: "B1", context: "接受提醒" },
  { id: 156, zh: "這不在我的職責範圍內", topic: "work", level_cefr: "B1", context: "拒絕分外事" },
  { id: 157, zh: "這個我可以學", topic: "work", level_cefr: "B1", context: "主動學習" },
  { id: 158, zh: "我們需要先做測試", topic: "work", level_cefr: "B1", context: "建議流程" },
  { id: 159, zh: "這個案子卡住了", topic: "work", level_cefr: "B1", context: "回報問題" },
  { id: 160, zh: "我需要你的支援", topic: "work", level_cefr: "B1", context: "求援" },
  { id: 161, zh: "我可以表達一下我的想法嗎", topic: "work", level_cefr: "B1", context: "爭取發言" },
  { id: 162, zh: "我覺得這個方向不太對", topic: "work", level_cefr: "B1", context: "婉轉反對" },
  { id: 163, zh: "我們先休息一下吧", topic: "work", level_cefr: "B1", context: "提議休息" },
  { id: 164, zh: "我剛剛沒聽清楚", topic: "work", level_cefr: "B1", context: "請求重述" },
  { id: 165, zh: "這份報告我明天交", topic: "work", level_cefr: "B1", context: "承諾期限" },
  { id: 166, zh: "可以幫我看一下嗎", topic: "work", level_cefr: "B1", context: "請對方 review" },
  { id: 167, zh: "我按照你說的改了", topic: "work", level_cefr: "B1", context: "回報修改完成" },
  { id: 168, zh: "這件事我盡量", topic: "work", level_cefr: "B1", context: "保留空間的承諾" },
  { id: 169, zh: "這個客戶很難搞", topic: "work", level_cefr: "B1", context: "抱怨客戶" },
  { id: 170, zh: "我下週一上班", topic: "work", level_cefr: "B1", context: "告知休假結束" },

  // ── B2 職場（30 題） ──
  { id: 171, zh: "這個我保留意見", topic: "work", level_cefr: "B2", context: "不表態" },
  { id: 172, zh: "我建議我們先緩一緩", topic: "work", level_cefr: "B2", context: "提議暫停" },
  { id: 173, zh: "我想從另一個角度思考", topic: "work", level_cefr: "B2", context: "重新切入" },
  { id: 174, zh: "這牽涉到很多層面", topic: "work", level_cefr: "B2", context: "複雜議題" },
  { id: 175, zh: "我們要先釐清需求", topic: "work", level_cefr: "B2", context: "專案討論" },
  { id: 176, zh: "這不是長久之計", topic: "work", level_cefr: "B2", context: "反對短期作法" },
  { id: 177, zh: "我想提個不一樣的看法", topic: "work", level_cefr: "B2", context: "提出異議" },
  { id: 178, zh: "我認為這個風險太高", topic: "work", level_cefr: "B2", context: "風險評估" },
  { id: 179, zh: "這決定可能會有後續影響", topic: "work", level_cefr: "B2", context: "提醒後果" },
  { id: 180, zh: "我們應該考慮替代方案", topic: "work", level_cefr: "B2", context: "提議 plan B" },
  { id: 181, zh: "這個做法治標不治本", topic: "work", level_cefr: "B2", context: "批判表面解法" },
  { id: 182, zh: "我覺得我們沒有掌握重點", topic: "work", level_cefr: "B2", context: "拉回主題" },
  { id: 183, zh: "這件事我想再深入研究", topic: "work", level_cefr: "B2", context: "需要時間" },
  { id: 184, zh: "就我目前掌握的資訊來看", topic: "work", level_cefr: "B2", context: "謹慎發言" },
  { id: 185, zh: "這個需要跨部門協調", topic: "work", level_cefr: "B2", context: "複雜專案" },
  { id: 186, zh: "我希望我們能達成共識", topic: "work", level_cefr: "B2", context: "尋求協議" },
  { id: 187, zh: "這件事我不便評論", topic: "work", level_cefr: "B2", context: "避免表態" },
  { id: 188, zh: "我需要更完整的背景資料", topic: "work", level_cefr: "B2", context: "要求資訊" },
  { id: 189, zh: "這個我必須回去跟團隊討論", topic: "work", level_cefr: "B2", context: "不當場決定" },
  { id: 190, zh: "我想強調一個重點", topic: "work", level_cefr: "B2", context: "會議發言" },
  { id: 191, zh: "我們不該犧牲品質", topic: "work", level_cefr: "B2", context: "堅持標準" },
  { id: 192, zh: "這可能會影響後續進度", topic: "work", level_cefr: "B2", context: "預警" },
  { id: 193, zh: "這個專案的優先順序需要重新排", topic: "work", level_cefr: "B2", context: "重新規劃" },
  { id: 194, zh: "我想聽你更詳細的想法", topic: "work", level_cefr: "B2", context: "深入對話" },
  { id: 195, zh: "我們需要一個明確的時程", topic: "work", level_cefr: "B2", context: "要求時程表" },
  { id: 196, zh: "這件事我會全權負責", topic: "work", level_cefr: "B2", context: "承擔責任" },
  { id: 197, zh: "這個提案需要再細化", topic: "work", level_cefr: "B2", context: "回饋意見" },
  { id: 198, zh: "我不希望到時候互相推責任", topic: "work", level_cefr: "B2", context: "預防衝突" },
  { id: 199, zh: "這個數據我需要再驗證", topic: "work", level_cefr: "B2", context: "謹慎態度" },
  { id: 200, zh: "這要從長計議", topic: "work", level_cefr: "B2", context: "延後複雜決定" },

  // ============================================================
  // 📂 情緒表達 emotion (100 題)
  // ============================================================

  // ── A2 情緒（30 題） ──
  { id: 201, zh: "我很開心", topic: "emotion", level_cefr: "A2", context: "表達快樂" },
  { id: 202, zh: "我很累", topic: "emotion", level_cefr: "A2", context: "身心疲憊" },
  { id: 203, zh: "我很難過", topic: "emotion", level_cefr: "A2", context: "情緒低落" },
  { id: 204, zh: "我生氣了", topic: "emotion", level_cefr: "A2", context: "表達憤怒" },
  { id: 205, zh: "我很興奮", topic: "emotion", level_cefr: "A2", context: "期待事件" },
  { id: 206, zh: "我有點害怕", topic: "emotion", level_cefr: "A2", context: "恐懼" },
  { id: 207, zh: "我很擔心你", topic: "emotion", level_cefr: "A2", context: "關心" },
  { id: 208, zh: "我覺得無聊", topic: "emotion", level_cefr: "A2", context: "沒事做" },
  { id: 209, zh: "我很驚訝", topic: "emotion", level_cefr: "A2", context: "意外" },
  { id: 210, zh: "我愛你", topic: "emotion", level_cefr: "A2", context: "表白" },
  { id: 211, zh: "我想你了", topic: "emotion", level_cefr: "A2", context: "思念" },
  { id: 212, zh: "我沒事", topic: "emotion", level_cefr: "A2", context: "被關心時" },
  { id: 213, zh: "別擔心", topic: "emotion", level_cefr: "A2", context: "安慰" },
  { id: 214, zh: "加油", topic: "emotion", level_cefr: "A2", context: "鼓勵" },
  { id: 215, zh: "對不起", topic: "emotion", level_cefr: "A2", context: "道歉" },
  { id: 216, zh: "沒關係", topic: "emotion", level_cefr: "A2", context: "接受道歉" },
  { id: 217, zh: "謝謝你", topic: "emotion", level_cefr: "A2", context: "感謝" },
  { id: 218, zh: "我很感動", topic: "emotion", level_cefr: "A2", context: "被打動" },
  { id: 219, zh: "我很滿意", topic: "emotion", level_cefr: "A2", context: "肯定結果" },
  { id: 220, zh: "我不喜歡這樣", topic: "emotion", level_cefr: "A2", context: "表達不適" },
  { id: 221, zh: "真的嗎", topic: "emotion", level_cefr: "A2", context: "驚訝回應" },
  { id: 222, zh: "太好了", topic: "emotion", level_cefr: "A2", context: "開心回應" },
  { id: 223, zh: "真倒楣", topic: "emotion", level_cefr: "A2", context: "抱怨運氣" },
  { id: 224, zh: "我覺得很好笑", topic: "emotion", level_cefr: "A2", context: "幽默" },
  { id: 225, zh: "我有點失望", topic: "emotion", level_cefr: "A2", context: "期待落空" },
  { id: 226, zh: "我嚇了一跳", topic: "emotion", level_cefr: "A2", context: "被嚇到" },
  { id: 227, zh: "我覺得很棒", topic: "emotion", level_cefr: "A2", context: "肯定" },
  { id: 228, zh: "我哭了", topic: "emotion", level_cefr: "A2", context: "情緒崩潰" },
  { id: 229, zh: "我笑出來了", topic: "emotion", level_cefr: "A2", context: "被逗笑" },
  { id: 230, zh: "我討厭這個", topic: "emotion", level_cefr: "A2", context: "厭惡" },

  // ── B1 情緒（40 題） ──
  { id: 231, zh: "你再這樣我就生氣囉", topic: "emotion", level_cefr: "B1", context: "半開玩笑警告" },
  { id: 232, zh: "我不是那個意思", topic: "emotion", level_cefr: "B1", context: "被誤會" },
  { id: 233, zh: "你很煩耶", topic: "emotion", level_cefr: "B1", context: "跟好朋友抱怨" },
  { id: 234, zh: "早知道就不來了", topic: "emotion", level_cefr: "B1", context: "後悔" },
  { id: 235, zh: "我真的受夠了", topic: "emotion", level_cefr: "B1", context: "抱怨" },
  { id: 236, zh: "我只是開玩笑的啦", topic: "emotion", level_cefr: "B1", context: "化解尷尬" },
  { id: 237, zh: "你想太多了", topic: "emotion", level_cefr: "B1", context: "安慰焦慮" },
  { id: 238, zh: "我沒事啦,真的", topic: "emotion", level_cefr: "B1", context: "被關心時" },
  { id: 239, zh: "這讓我覺得有點尷尬", topic: "emotion", level_cefr: "B1", context: "描述場面" },
  { id: 240, zh: "我超感動的", topic: "emotion", level_cefr: "B1", context: "被打動" },
  { id: 241, zh: "這讓我壓力很大", topic: "emotion", level_cefr: "B1", context: "工作狀態" },
  { id: 242, zh: "我有點難過", topic: "emotion", level_cefr: "B1", context: "表達情緒" },
  { id: 243, zh: "你讓我很失望", topic: "emotion", level_cefr: "B1", context: "表達不滿" },
  { id: 244, zh: "我完全不在意", topic: "emotion", level_cefr: "B1", context: "無所謂" },
  { id: 245, zh: "這不關我的事", topic: "emotion", level_cefr: "B1", context: "撇清" },
  { id: 246, zh: "我真的很慶幸", topic: "emotion", level_cefr: "B1", context: "慶幸" },
  { id: 247, zh: "這讓我覺得不好意思", topic: "emotion", level_cefr: "B1", context: "被稱讚" },
  { id: 248, zh: "我怕我會後悔", topic: "emotion", level_cefr: "B1", context: "猶豫" },
  { id: 249, zh: "我很內疚", topic: "emotion", level_cefr: "B1", context: "做錯事" },
  { id: 250, zh: "我感到很孤單", topic: "emotion", level_cefr: "B1", context: "寂寞" },
  { id: 251, zh: "我有點嫉妒", topic: "emotion", level_cefr: "B1", context: "羨慕變嫉妒" },
  { id: 252, zh: "我覺得好糗", topic: "emotion", level_cefr: "B1", context: "出糗" },
  { id: 253, zh: "我真的很緊張", topic: "emotion", level_cefr: "B1", context: "面試、上台" },
  { id: 254, zh: "我心情很複雜", topic: "emotion", level_cefr: "B1", context: "多重情緒" },
  { id: 255, zh: "我覺得被忽視了", topic: "emotion", level_cefr: "B1", context: "感到被冷落" },
  { id: 256, zh: "我很感激你", topic: "emotion", level_cefr: "B1", context: "深度感謝" },
  { id: 257, zh: "我沒辦法放下", topic: "emotion", level_cefr: "B1", context: "放不下某事" },
  { id: 258, zh: "我心裡有點不是滋味", topic: "emotion", level_cefr: "B1", context: "微妙不快" },
  { id: 259, zh: "我很心疼你", topic: "emotion", level_cefr: "B1", context: "捨不得" },
  { id: 260, zh: "我真的很無奈", topic: "emotion", level_cefr: "B1", context: "無能為力" },
  { id: 261, zh: "我被你感動到了", topic: "emotion", level_cefr: "B1", context: "深深觸動" },
  { id: 262, zh: "我覺得好煩躁", topic: "emotion", level_cefr: "B1", context: "煩悶" },
  { id: 263, zh: "這讓我很有成就感", topic: "emotion", level_cefr: "B1", context: "完成事情" },
  { id: 264, zh: "我有點不甘心", topic: "emotion", level_cefr: "B1", context: "輸了比賽" },
  { id: 265, zh: "我替你感到高興", topic: "emotion", level_cefr: "B1", context: "為朋友開心" },
  { id: 266, zh: "我真的很佩服你", topic: "emotion", level_cefr: "B1", context: "敬佩" },
  { id: 267, zh: "我其實有點害羞", topic: "emotion", level_cefr: "B1", context: "承認害羞" },
  { id: 268, zh: "我覺得好虧欠你", topic: "emotion", level_cefr: "B1", context: "感到虧欠" },
  { id: 269, zh: "這事讓我心力交瘁", topic: "emotion", level_cefr: "B1", context: "身心俱疲" },
  { id: 270, zh: "我已經看開了", topic: "emotion", level_cefr: "B1", context: "釋懷" },

  // ── B2 情緒（30 題） ──
  { id: 271, zh: "我覺得很委屈", topic: "emotion", level_cefr: "B2", context: "被誤解" },
  { id: 272, zh: "你不懂我在想什麼", topic: "emotion", level_cefr: "B2", context: "爭執" },
  { id: 273, zh: "你這樣讓我很為難", topic: "emotion", level_cefr: "B2", context: "被迫選擇" },
  { id: 274, zh: "我說不出那種感覺", topic: "emotion", level_cefr: "B2", context: "難以形容的情緒" },
  { id: 275, zh: "我的情緒有點低落", topic: "emotion", level_cefr: "B2", context: "輕度憂鬱" },
  { id: 276, zh: "我覺得被背叛了", topic: "emotion", level_cefr: "B2", context: "信任受挫" },
  { id: 277, zh: "我一直在壓抑自己", topic: "emotion", level_cefr: "B2", context: "壓抑情緒" },
  { id: 278, zh: "我想把這些都釋放出來", topic: "emotion", level_cefr: "B2", context: "情感宣洩" },
  { id: 279, zh: "這種感覺我沒辦法形容", topic: "emotion", level_cefr: "B2", context: "複雜情感" },
  { id: 280, zh: "我感到很迷惘", topic: "emotion", level_cefr: "B2", context: "人生方向" },
  { id: 281, zh: "這讓我徹底失望", topic: "emotion", level_cefr: "B2", context: "深度失望" },
  { id: 282, zh: "我一直走不出來", topic: "emotion", level_cefr: "B2", context: "創傷難癒" },
  { id: 283, zh: "我需要一個人靜一靜", topic: "emotion", level_cefr: "B2", context: "獨處需求" },
  { id: 284, zh: "我有種莫名的焦慮", topic: "emotion", level_cefr: "B2", context: "無端焦慮" },
  { id: 285, zh: "我對這件事很敏感", topic: "emotion", level_cefr: "B2", context: "觸及痛點" },
  { id: 286, zh: "我沒辦法假裝沒事", topic: "emotion", level_cefr: "B2", context: "無法裝作沒事" },
  { id: 287, zh: "這動搖了我的信心", topic: "emotion", level_cefr: "B2", context: "自信受挫" },
  { id: 288, zh: "我覺得被徹底掏空", topic: "emotion", level_cefr: "B2", context: "極度疲憊" },
  { id: 289, zh: "我的內心五味雜陳", topic: "emotion", level_cefr: "B2", context: "複雜情緒" },
  { id: 290, zh: "我一直在跟自己拉扯", topic: "emotion", level_cefr: "B2", context: "內心矛盾" },
  { id: 291, zh: "這件事讓我重新認識自己", topic: "emotion", level_cefr: "B2", context: "自我覺察" },
  { id: 292, zh: "我一度以為我撐不下去", topic: "emotion", level_cefr: "B2", context: "度過難關" },
  { id: 293, zh: "我覺得被情感勒索了", topic: "emotion", level_cefr: "B2", context: "心理壓迫" },
  { id: 294, zh: "這是我一輩子的遺憾", topic: "emotion", level_cefr: "B2", context: "深度遺憾" },
  { id: 295, zh: "我試著原諒,但還沒做到", topic: "emotion", level_cefr: "B2", context: "原諒困難" },
  { id: 296, zh: "這觸碰到我的底線", topic: "emotion", level_cefr: "B2", context: "越界" },
  { id: 297, zh: "我已經麻木了", topic: "emotion", level_cefr: "B2", context: "情感麻痺" },
  { id: 298, zh: "這讓我很有同理心", topic: "emotion", level_cefr: "B2", context: "感同身受" },
  { id: 299, zh: "我的心境已經不同了", topic: "emotion", level_cefr: "B2", context: "心態改變" },
  { id: 300, zh: "我想用不同的方式面對", topic: "emotion", level_cefr: "B2", context: "嘗試改變" },

  // ============================================================
  // 📂 旅遊 travel (100 題)
  // ============================================================

  // ── A2 旅遊（40 題） ──
  { id: 301, zh: "請問廁所在哪裡", topic: "travel", level_cefr: "A2", context: "機場、餐廳" },
  { id: 302, zh: "可以幫我拍張照嗎", topic: "travel", level_cefr: "A2", context: "請路人幫忙" },
  { id: 303, zh: "這個多少錢", topic: "travel", level_cefr: "A2", context: "購物" },
  { id: 304, zh: "可以給我菜單嗎", topic: "travel", level_cefr: "A2", context: "點餐" },
  { id: 305, zh: "我想換錢", topic: "travel", level_cefr: "A2", context: "兌換外幣" },
  { id: 306, zh: "可以刷卡嗎", topic: "travel", level_cefr: "A2", context: "結帳" },
  { id: 307, zh: "我要一張去東京的票", topic: "travel", level_cefr: "A2", context: "買車票" },
  { id: 308, zh: "我的行李在哪裡拿", topic: "travel", level_cefr: "A2", context: "機場提領" },
  { id: 309, zh: "我迷路了", topic: "travel", level_cefr: "A2", context: "求助" },
  { id: 310, zh: "我要 check-in", topic: "travel", level_cefr: "A2", context: "飯店入住" },
  { id: 311, zh: "我訂了兩晚的房間", topic: "travel", level_cefr: "A2", context: "飯店" },
  { id: 312, zh: "請問現在幾點", topic: "travel", level_cefr: "A2", context: "詢問時間" },
  { id: 313, zh: "我要一杯水", topic: "travel", level_cefr: "A2", context: "點飲料" },
  { id: 314, zh: "不要冰", topic: "travel", level_cefr: "A2", context: "特別要求" },
  { id: 315, zh: "這個很辣嗎", topic: "travel", level_cefr: "A2", context: "點餐確認" },
  { id: 316, zh: "我要內用", topic: "travel", level_cefr: "A2", context: "餐廳點餐" },
  { id: 317, zh: "我要外帶", topic: "travel", level_cefr: "A2", context: "餐廳點餐" },
  { id: 318, zh: "我要一個大份的", topic: "travel", level_cefr: "A2", context: "點餐" },
  { id: 319, zh: "可以加辣嗎", topic: "travel", level_cefr: "A2", context: "客製化" },
  { id: 320, zh: "不要加糖", topic: "travel", level_cefr: "A2", context: "飲料客製" },
  { id: 321, zh: "買單,謝謝", topic: "travel", level_cefr: "A2", context: "結帳" },
  { id: 322, zh: "可以分開結帳嗎", topic: "travel", level_cefr: "A2", context: "AA" },
  { id: 323, zh: "這附近有地鐵站嗎", topic: "travel", level_cefr: "A2", context: "問路" },
  { id: 324, zh: "怎麼去車站", topic: "travel", level_cefr: "A2", context: "問路" },
  { id: 325, zh: "我要去機場", topic: "travel", level_cefr: "A2", context: "搭車" },
  { id: 326, zh: "請載我到這個地址", topic: "travel", level_cefr: "A2", context: "叫車" },
  { id: 327, zh: "我要下車", topic: "travel", level_cefr: "A2", context: "下車" },
  { id: 328, zh: "我要去這裡", topic: "travel", level_cefr: "A2", context: "指地圖" },
  { id: 329, zh: "請開快一點", topic: "travel", level_cefr: "A2", context: "趕時間" },
  { id: 330, zh: "停在這裡就好", topic: "travel", level_cefr: "A2", context: "下車" },
  { id: 331, zh: "這個位子有人嗎", topic: "travel", level_cefr: "A2", context: "確認座位" },
  { id: 332, zh: "請問這班車去哪裡", topic: "travel", level_cefr: "A2", context: "確認班次" },
  { id: 333, zh: "下一班車是幾點", topic: "travel", level_cefr: "A2", context: "時刻" },
  { id: 334, zh: "我找不到我的行李", topic: "travel", level_cefr: "A2", context: "行李遺失" },
  { id: 335, zh: "我的護照掉了", topic: "travel", level_cefr: "A2", context: "求助警察" },
  { id: 336, zh: "最近的醫院在哪裡", topic: "travel", level_cefr: "A2", context: "緊急" },
  { id: 337, zh: "我不舒服", topic: "travel", level_cefr: "A2", context: "身體狀況" },
  { id: 338, zh: "我對花生過敏", topic: "travel", level_cefr: "A2", context: "飲食重要資訊" },
  { id: 339, zh: "我不吃牛肉", topic: "travel", level_cefr: "A2", context: "飲食限制" },
  { id: 340, zh: "這個很好吃", topic: "travel", level_cefr: "A2", context: "稱讚食物" },

  // ── B1 旅遊（35 題） ──
  { id: 341, zh: "這個可以帶上飛機嗎", topic: "travel", level_cefr: "B1", context: "安檢" },
  { id: 342, zh: "我想換個房間", topic: "travel", level_cefr: "B1", context: "飯店櫃檯" },
  { id: 343, zh: "這家餐廳要等多久", topic: "travel", level_cefr: "B1", context: "排隊" },
  { id: 344, zh: "可以幫我加熱一下嗎", topic: "travel", level_cefr: "B1", context: "便利商店" },
  { id: 345, zh: "這附近有便利商店嗎", topic: "travel", level_cefr: "B1", context: "問路" },
  { id: 346, zh: "我想取消訂房", topic: "travel", level_cefr: "B1", context: "飯店" },
  { id: 347, zh: "飯店有提供早餐嗎", topic: "travel", level_cefr: "B1", context: "確認服務" },
  { id: 348, zh: "這個可以外帶嗎", topic: "travel", level_cefr: "B1", context: "餐廳" },
  { id: 349, zh: "我訂的是雙人房", topic: "travel", level_cefr: "B1", context: "check-in 糾正" },
  { id: 350, zh: "我的行李還沒出來", topic: "travel", level_cefr: "B1", context: "機場行李" },
  { id: 351, zh: "請問這個可以退稅嗎", topic: "travel", level_cefr: "B1", context: "機場購物" },
  { id: 352, zh: "我想延長退房時間", topic: "travel", level_cefr: "B1", context: "飯店" },
  { id: 353, zh: "這個行程大概要多久", topic: "travel", level_cefr: "B1", context: "旅遊諮詢" },
  { id: 354, zh: "這張票可以退嗎", topic: "travel", level_cefr: "B1", context: "退票" },
  { id: 355, zh: "我要改班機", topic: "travel", level_cefr: "B1", context: "機場櫃檯" },
  { id: 356, zh: "這個景點值得去嗎", topic: "travel", level_cefr: "B1", context: "旅遊建議" },
  { id: 357, zh: "這裡可以拍照嗎", topic: "travel", level_cefr: "B1", context: "確認規則" },
  { id: 358, zh: "我可以試穿嗎", topic: "travel", level_cefr: "B1", context: "購物" },
  { id: 359, zh: "有其他顏色嗎", topic: "travel", level_cefr: "B1", context: "購物" },
  { id: 360, zh: "可以算便宜一點嗎", topic: "travel", level_cefr: "B1", context: "議價" },
  { id: 361, zh: "我在找紀念品", topic: "travel", level_cefr: "B1", context: "購物" },
  { id: 362, zh: "房間的 WiFi 密碼是什麼", topic: "travel", level_cefr: "B1", context: "飯店" },
  { id: 363, zh: "熱水好像壞了", topic: "travel", level_cefr: "B1", context: "飯店問題" },
  { id: 364, zh: "隔壁房間太吵了", topic: "travel", level_cefr: "B1", context: "飯店投訴" },
  { id: 365, zh: "我要多拿幾張毛巾", topic: "travel", level_cefr: "B1", context: "飯店服務" },
  { id: 366, zh: "請問要轉幾次車", topic: "travel", level_cefr: "B1", context: "交通" },
  { id: 367, zh: "這附近治安好嗎", topic: "travel", level_cefr: "B1", context: "安全諮詢" },
  { id: 368, zh: "這家店是當地人常去的嗎", topic: "travel", level_cefr: "B1", context: "找道地美食" },
  { id: 369, zh: "有推薦的路線嗎", topic: "travel", level_cefr: "B1", context: "旅遊建議" },
  { id: 370, zh: "我想買個當地特產", topic: "travel", level_cefr: "B1", context: "購物需求" },
  { id: 371, zh: "我被多收錢了", topic: "travel", level_cefr: "B1", context: "帳單爭議" },
  { id: 372, zh: "我要開收據", topic: "travel", level_cefr: "B1", context: "結帳" },
  { id: 373, zh: "我今天想悠閒一點", topic: "travel", level_cefr: "B1", context: "調整行程" },
  { id: 374, zh: "這個天氣適合走步道嗎", topic: "travel", level_cefr: "B1", context: "戶外活動" },
  { id: 375, zh: "我們走散了", topic: "travel", level_cefr: "B1", context: "找同伴" },

  // ── B2 旅遊（25 題） ──
  { id: 376, zh: "我想深度體驗當地文化", topic: "travel", level_cefr: "B2", context: "旅遊理念" },
  { id: 377, zh: "我不太喜歡觀光客多的地方", topic: "travel", level_cefr: "B2", context: "偏好小眾" },
  { id: 378, zh: "這個行程讓我印象深刻", topic: "travel", level_cefr: "B2", context: "分享心得" },
  { id: 379, zh: "我想找個沒那麼商業化的地方", topic: "travel", level_cefr: "B2", context: "旅遊偏好" },
  { id: 380, zh: "這次旅行徹底改變了我的想法", topic: "travel", level_cefr: "B2", context: "深度反思" },
  { id: 381, zh: "我想找在地嚮導", topic: "travel", level_cefr: "B2", context: "旅遊服務" },
  { id: 382, zh: "旅行真的能打開眼界", topic: "travel", level_cefr: "B2", context: "旅行感想" },
  { id: 383, zh: "我想規劃得更彈性一點", topic: "travel", level_cefr: "B2", context: "自由行" },
  { id: 384, zh: "這個城市的氛圍很特別", topic: "travel", level_cefr: "B2", context: "城市印象" },
  { id: 385, zh: "我比較喜歡慢活的旅行方式", topic: "travel", level_cefr: "B2", context: "旅遊風格" },
  { id: 386, zh: "這讓我想要重新規劃行程", topic: "travel", level_cefr: "B2", context: "臨時調整" },
  { id: 387, zh: "我不想被行程綁死", topic: "travel", level_cefr: "B2", context: "彈性行程" },
  { id: 388, zh: "當地人非常熱情", topic: "travel", level_cefr: "B2", context: "文化觀察" },
  { id: 389, zh: "文化差異真的很有趣", topic: "travel", level_cefr: "B2", context: "跨文化" },
  { id: 390, zh: "我想體驗真正的在地生活", topic: "travel", level_cefr: "B2", context: "深度旅行" },
  { id: 391, zh: "這個地方被嚴重低估了", topic: "travel", level_cefr: "B2", context: "隱藏景點" },
  { id: 392, zh: "我覺得這是此行的亮點", topic: "travel", level_cefr: "B2", context: "旅程高潮" },
  { id: 393, zh: "我想嘗試一些冒險的活動", topic: "travel", level_cefr: "B2", context: "極限運動" },
  { id: 394, zh: "旅途中最美的是那些意外", topic: "travel", level_cefr: "B2", context: "旅行哲學" },
  { id: 395, zh: "這讓我對這個國家有全新認識", topic: "travel", level_cefr: "B2", context: "認識改觀" },
  { id: 396, zh: "我把這列在我的人生清單", topic: "travel", level_cefr: "B2", context: "bucket list" },
  { id: 397, zh: "我希望以後還能再回來", topic: "travel", level_cefr: "B2", context: "旅行尾聲" },
  { id: 398, zh: "這次旅行讓我重新充電", topic: "travel", level_cefr: "B2", context: "身心放鬆" },
  { id: 399, zh: "這家餐廳根本是隱藏版的", topic: "travel", level_cefr: "B2", context: "推薦私房" },
  { id: 400, zh: "風景美到讓我說不出話", topic: "travel", level_cefr: "B2", context: "震撼" },

  // ============================================================
  // 📂 意見表達 opinion (100 題)
  // ============================================================

  // ── A2 意見（30 題） ──
  { id: 401, zh: "我覺得不錯", topic: "opinion", level_cefr: "A2", context: "簡單肯定" },
  { id: 402, zh: "我不同意", topic: "opinion", level_cefr: "A2", context: "反對" },
  { id: 403, zh: "我也是這樣想", topic: "opinion", level_cefr: "A2", context: "贊同" },
  { id: 404, zh: "我不知道怎麼說", topic: "opinion", level_cefr: "A2", context: "表達困難" },
  { id: 405, zh: "可以再說一次嗎", topic: "opinion", level_cefr: "A2", context: "沒聽懂" },
  { id: 406, zh: "我想問一個問題", topic: "opinion", level_cefr: "A2", context: "提問" },
  { id: 407, zh: "我想聽你的想法", topic: "opinion", level_cefr: "A2", context: "徵詢" },
  { id: 408, zh: "這是我的看法", topic: "opinion", level_cefr: "A2", context: "表態" },
  { id: 409, zh: "我覺得兩個都可以", topic: "opinion", level_cefr: "A2", context: "中立" },
  { id: 410, zh: "我喜歡這個", topic: "opinion", level_cefr: "A2", context: "表達偏好" },
  { id: 411, zh: "我不喜歡那個", topic: "opinion", level_cefr: "A2", context: "負面偏好" },
  { id: 412, zh: "我覺得很重要", topic: "opinion", level_cefr: "A2", context: "強調" },
  { id: 413, zh: "我沒意見", topic: "opinion", level_cefr: "A2", context: "中立" },
  { id: 414, zh: "你覺得呢", topic: "opinion", level_cefr: "A2", context: "徵詢對方" },
  { id: 415, zh: "這個比較好", topic: "opinion", level_cefr: "A2", context: "比較" },
  { id: 416, zh: "我覺得不太好", topic: "opinion", level_cefr: "A2", context: "婉轉負評" },
  { id: 417, zh: "聽起來不錯", topic: "opinion", level_cefr: "A2", context: "對提案" },
  { id: 418, zh: "我需要時間想想", topic: "opinion", level_cefr: "A2", context: "延後表態" },
  { id: 419, zh: "好主意", topic: "opinion", level_cefr: "A2", context: "稱讚點子" },
  { id: 420, zh: "有道理", topic: "opinion", level_cefr: "A2", context: "認同" },
  { id: 421, zh: "我不確定", topic: "opinion", level_cefr: "A2", context: "不確定" },
  { id: 422, zh: "這很困難", topic: "opinion", level_cefr: "A2", context: "難度高" },
  { id: 423, zh: "這很簡單", topic: "opinion", level_cefr: "A2", context: "輕鬆" },
  { id: 424, zh: "這有可能", topic: "opinion", level_cefr: "A2", context: "可能性" },
  { id: 425, zh: "這不可能", topic: "opinion", level_cefr: "A2", context: "否定" },
  { id: 426, zh: "我會試試看", topic: "opinion", level_cefr: "A2", context: "意願" },
  { id: 427, zh: "我不想", topic: "opinion", level_cefr: "A2", context: "拒絕" },
  { id: 428, zh: "我願意", topic: "opinion", level_cefr: "A2", context: "同意" },
  { id: 429, zh: "我喜歡這個點子", topic: "opinion", level_cefr: "A2", context: "支持提案" },
  { id: 430, zh: "這個太貴了", topic: "opinion", level_cefr: "A2", context: "成本評估" },

  // ── B1 意見（35 題） ──
  { id: 431, zh: "我覺得這樣做不太合適", topic: "opinion", level_cefr: "B1", context: "委婉反對" },
  { id: 432, zh: "我想聽聽看你的意見", topic: "opinion", level_cefr: "B1", context: "徵詢想法" },
  { id: 433, zh: "老實說,我不太同意", topic: "opinion", level_cefr: "B1", context: "禮貌異議" },
  { id: 434, zh: "我可以換個方式說嗎", topic: "opinion", level_cefr: "B1", context: "重新表達" },
  { id: 435, zh: "讓我釐清一下", topic: "opinion", level_cefr: "B1", context: "確認意思" },
  { id: 436, zh: "我有一點不同的看法", topic: "opinion", level_cefr: "B1", context: "婉轉不同意" },
  { id: 437, zh: "我懂你的意思,但是", topic: "opinion", level_cefr: "B1", context: "不完全同意" },
  { id: 438, zh: "我覺得重點應該是", topic: "opinion", level_cefr: "B1", context: "拉回主題" },
  { id: 439, zh: "這不是我想表達的", topic: "opinion", level_cefr: "B1", context: "被誤解" },
  { id: 440, zh: "我想補充一下", topic: "opinion", level_cefr: "B1", context: "加入討論" },
  { id: 441, zh: "你可以再解釋清楚一點嗎", topic: "opinion", level_cefr: "B1", context: "請求澄清" },
  { id: 442, zh: "我認為這樣做比較好", topic: "opinion", level_cefr: "B1", context: "提出建議" },
  { id: 443, zh: "我剛剛想到一個點", topic: "opinion", level_cefr: "B1", context: "討論靈感" },
  { id: 444, zh: "這只是我個人的想法", topic: "opinion", level_cefr: "B1", context: "主觀" },
  { id: 445, zh: "總結來說", topic: "opinion", level_cefr: "B1", context: "做結論" },
  { id: 446, zh: "我同意這個方向", topic: "opinion", level_cefr: "B1", context: "認同提案" },
  { id: 447, zh: "我不完全同意", topic: "opinion", level_cefr: "B1", context: "部分反對" },
  { id: 448, zh: "這個需要再討論", topic: "opinion", level_cefr: "B1", context: "延續討論" },
  { id: 449, zh: "我想提出一個問題", topic: "opinion", level_cefr: "B1", context: "提問" },
  { id: 450, zh: "我想確認一件事", topic: "opinion", level_cefr: "B1", context: "確認資訊" },
  { id: 451, zh: "這個點很關鍵", topic: "opinion", level_cefr: "B1", context: "強調重點" },
  { id: 452, zh: "我完全能理解你的意思", topic: "opinion", level_cefr: "B1", context: "表示理解" },
  { id: 453, zh: "這值得我們深入討論", topic: "opinion", level_cefr: "B1", context: "議題重要" },
  { id: 454, zh: "我有幾個疑問", topic: "opinion", level_cefr: "B1", context: "連續提問" },
  { id: 455, zh: "這其實有兩面", topic: "opinion", level_cefr: "B1", context: "雙面觀點" },
  { id: 456, zh: "我傾向前者", topic: "opinion", level_cefr: "B1", context: "表達偏好" },
  { id: 457, zh: "這個論點有道理", topic: "opinion", level_cefr: "B1", context: "認可論述" },
  { id: 458, zh: "我覺得這種說法太武斷", topic: "opinion", level_cefr: "B1", context: "反駁絕對論" },
  { id: 459, zh: "你這樣說我就明白了", topic: "opinion", level_cefr: "B1", context: "被說服" },
  { id: 460, zh: "這個例子很有說服力", topic: "opinion", level_cefr: "B1", context: "認可舉例" },
  { id: 461, zh: "這個想法還需要再想想", topic: "opinion", level_cefr: "B1", context: "保留空間" },
  { id: 462, zh: "我認為這件事要謹慎處理", topic: "opinion", level_cefr: "B1", context: "謹慎態度" },
  { id: 463, zh: "我支持這個提議", topic: "opinion", level_cefr: "B1", context: "表態支持" },
  { id: 464, zh: "這樣說可能太籠統了", topic: "opinion", level_cefr: "B1", context: "要求具體" },
  { id: 465, zh: "我想問一個比較直接的問題", topic: "opinion", level_cefr: "B1", context: "直白提問" },

  // ── B2 意見（35 題） ──
  { id: 466, zh: "我想從另一個角度看這件事", topic: "opinion", level_cefr: "B2", context: "新觀點" },
  { id: 467, zh: "這個我保留意見", topic: "opinion", level_cefr: "B2", context: "不表態" },
  { id: 468, zh: "這件事有很多面向可以看", topic: "opinion", level_cefr: "B2", context: "複雜議題" },
  { id: 469, zh: "就這個議題而言", topic: "opinion", level_cefr: "B2", context: "正式討論" },
  { id: 470, zh: "我沒辦法接受這種說法", topic: "opinion", level_cefr: "B2", context: "強烈反對" },
  { id: 471, zh: "這個論點站不住腳", topic: "opinion", level_cefr: "B2", context: "反駁" },
  { id: 472, zh: "我認為我們應該更深入探討", topic: "opinion", level_cefr: "B2", context: "深入討論" },
  { id: 473, zh: "這個推論有邏輯漏洞", topic: "opinion", level_cefr: "B2", context: "理性批判" },
  { id: 474, zh: "我覺得這已經偏題了", topic: "opinion", level_cefr: "B2", context: "拉回主題" },
  { id: 475, zh: "我想提出一個反例", topic: "opinion", level_cefr: "B2", context: "反證" },
  { id: 476, zh: "這說法過於簡化", topic: "opinion", level_cefr: "B2", context: "批評簡化" },
  { id: 477, zh: "我們需要區分幾個概念", topic: "opinion", level_cefr: "B2", context: "概念釐清" },
  { id: 478, zh: "這兩者不該混為一談", topic: "opinion", level_cefr: "B2", context: "概念區分" },
  { id: 479, zh: "我認同大方向,但細節有疑慮", topic: "opinion", level_cefr: "B2", context: "部分同意" },
  { id: 480, zh: "這需要更多實證支持", topic: "opinion", level_cefr: "B2", context: "要求證據" },
  { id: 481, zh: "這只是我的觀察,不是結論", topic: "opinion", level_cefr: "B2", context: "謹慎表態" },
  { id: 482, zh: "我試著站在反方思考", topic: "opinion", level_cefr: "B2", context: "反面思考" },
  { id: 483, zh: "這在邏輯上說得通嗎", topic: "opinion", level_cefr: "B2", context: "質疑邏輯" },
  { id: 484, zh: "我們應該聚焦在真正的問題", topic: "opinion", level_cefr: "B2", context: "聚焦核心" },
  { id: 485, zh: "這涉及到根本的價值觀", topic: "opinion", level_cefr: "B2", context: "價值討論" },
  { id: 486, zh: "這在實務上很難執行", topic: "opinion", level_cefr: "B2", context: "實務考量" },
  { id: 487, zh: "我傾向保留判斷", topic: "opinion", level_cefr: "B2", context: "暫不表態" },
  { id: 488, zh: "這種二分法太簡化", topic: "opinion", level_cefr: "B2", context: "拒絕二元" },
  { id: 489, zh: "脈絡很重要", topic: "opinion", level_cefr: "B2", context: "強調情境" },
  { id: 490, zh: "這只是表象,不是根源", topic: "opinion", level_cefr: "B2", context: "深層分析" },
  { id: 491, zh: "我想挑戰這個假設", topic: "opinion", level_cefr: "B2", context: "質疑前提" },
  { id: 492, zh: "我們得先定義清楚", topic: "opinion", level_cefr: "B2", context: "術語釐清" },
  { id: 493, zh: "這個結論下得太快", topic: "opinion", level_cefr: "B2", context: "反對倉促結論" },
  { id: 494, zh: "我認為這是短視的決定", topic: "opinion", level_cefr: "B2", context: "批評短視" },
  { id: 495, zh: "要從長遠來看", topic: "opinion", level_cefr: "B2", context: "長期觀點" },
  { id: 496, zh: "這其實是個偽議題", topic: "opinion", level_cefr: "B2", context: "批評議題" },
  { id: 497, zh: "我沒辦法毫無保留地支持", topic: "opinion", level_cefr: "B2", context: "保留支持" },
  { id: 498, zh: "這有可能造成反效果", topic: "opinion", level_cefr: "B2", context: "警示後果" },
  { id: 499, zh: "讓我們回到最初的問題", topic: "opinion", level_cefr: "B2", context: "回歸本質" },
  { id: 500, zh: "我覺得這個討論很有啟發", topic: "opinion", level_cefr: "B2", context: "肯定對話" },

  // ============================================================
  // 📂 消費生活 shopping (70 題) - 餐廳點餐 + 購物/收銀台
  // ============================================================

  // ── A2 消費生活（30 題） ──
  // 餐廳點餐 (A2, 15 題)
  { id: 501, zh: "兩位,謝謝", topic: "shopping", level_cefr: "A2", context: "進餐廳告知人數" },
  { id: 502, zh: "我有訂位", topic: "shopping", level_cefr: "A2", context: "餐廳櫃檯" },
  { id: 503, zh: "我要靠窗的位子", topic: "shopping", level_cefr: "A2", context: "選座位" },
  { id: 504, zh: "請給我菜單", topic: "shopping", level_cefr: "A2", context: "點餐前" },
  { id: 505, zh: "我要點餐", topic: "shopping", level_cefr: "A2", context: "叫服務生" },
  { id: 506, zh: "我要一份沙拉", topic: "shopping", level_cefr: "A2", context: "點菜" },
  { id: 507, zh: "我要中杯熱拿鐵", topic: "shopping", level_cefr: "A2", context: "咖啡店" },
  { id: 508, zh: "不要加冰塊", topic: "shopping", level_cefr: "A2", context: "客製飲料" },
  { id: 509, zh: "少糖,謝謝", topic: "shopping", level_cefr: "A2", context: "飲料客製" },
  { id: 510, zh: "可以再給我一杯水嗎", topic: "shopping", level_cefr: "A2", context: "續杯" },
  { id: 511, zh: "可以給我叉子嗎", topic: "shopping", level_cefr: "A2", context: "要餐具" },
  { id: 512, zh: "這個可以分享嗎", topic: "shopping", level_cefr: "A2", context: "分食確認" },
  { id: 513, zh: "我要買單", topic: "shopping", level_cefr: "A2", context: "結帳" },
  { id: 514, zh: "幫我分開結", topic: "shopping", level_cefr: "A2", context: "AA 制" },
  { id: 515, zh: "我要收據", topic: "shopping", level_cefr: "A2", context: "結帳要求" },

  // 購物/收銀台 (A2, 15 題)
  { id: 516, zh: "這個我要了", topic: "shopping", level_cefr: "A2", context: "決定購買" },
  { id: 517, zh: "有中號的嗎", topic: "shopping", level_cefr: "A2", context: "衣服尺寸" },
  { id: 518, zh: "我可以試穿嗎", topic: "shopping", level_cefr: "A2", context: "衣服" },
  { id: 519, zh: "這個有折扣嗎", topic: "shopping", level_cefr: "A2", context: "問價" },
  { id: 520, zh: "我只是看看", topic: "shopping", level_cefr: "A2", context: "婉拒店員" },
  { id: 521, zh: "在哪裡結帳", topic: "shopping", level_cefr: "A2", context: "找收銀台" },
  { id: 522, zh: "我要用信用卡付", topic: "shopping", level_cefr: "A2", context: "付款方式" },
  { id: 523, zh: "我要用現金付", topic: "shopping", level_cefr: "A2", context: "付款方式" },
  { id: 524, zh: "要袋子嗎我自己有帶", topic: "shopping", level_cefr: "A2", context: "環保袋" },
  { id: 525, zh: "這個可以退嗎", topic: "shopping", level_cefr: "A2", context: "退貨" },
  { id: 526, zh: "我有會員卡", topic: "shopping", level_cefr: "A2", context: "結帳" },
  { id: 527, zh: "這個在特價嗎", topic: "shopping", level_cefr: "A2", context: "確認折扣" },
  { id: 528, zh: "有沒有其他顏色", topic: "shopping", level_cefr: "A2", context: "挑商品" },
  { id: 529, zh: "這件是最後一件嗎", topic: "shopping", level_cefr: "A2", context: "庫存" },
  { id: 530, zh: "再給我看一下那個", topic: "shopping", level_cefr: "A2", context: "指商品" },

  // ── B1 消費生活（25 題） ──
  // 餐廳點餐 (B1, 13 題)
  { id: 531, zh: "這道菜有什麼特別的嗎", topic: "shopping", level_cefr: "B1", context: "問菜色" },
  { id: 532, zh: "有什麼推薦的嗎", topic: "shopping", level_cefr: "B1", context: "問推薦" },
  { id: 533, zh: "我對海鮮過敏", topic: "shopping", level_cefr: "B1", context: "點餐重要資訊" },
  { id: 534, zh: "可以不要放洋蔥嗎", topic: "shopping", level_cefr: "B1", context: "客製" },
  { id: 535, zh: "這個要等多久", topic: "shopping", level_cefr: "B1", context: "問上菜時間" },
  { id: 536, zh: "我們餐點好像還沒來", topic: "shopping", level_cefr: "B1", context: "提醒服務生" },
  { id: 537, zh: "我點的不是這個", topic: "shopping", level_cefr: "B1", context: "上錯菜" },
  { id: 538, zh: "這個好像沒熟", topic: "shopping", level_cefr: "B1", context: "食物問題" },
  { id: 539, zh: "可以幫我加熱嗎", topic: "shopping", level_cefr: "B1", context: "食物涼了" },
  { id: 540, zh: "吃不完可以打包嗎", topic: "shopping", level_cefr: "B1", context: "外帶剩餘" },
  { id: 541, zh: "服務費有含在裡面嗎", topic: "shopping", level_cefr: "B1", context: "結帳確認" },
  { id: 542, zh: "這家餐廳生意真好", topic: "shopping", level_cefr: "B1", context: "閒聊" },
  { id: 543, zh: "下次還要再來", topic: "shopping", level_cefr: "B1", context: "讚美餐廳" },

  // 購物/收銀台 (B1, 12 題)
  { id: 544, zh: "可以算我便宜一點嗎", topic: "shopping", level_cefr: "B1", context: "議價" },
  { id: 545, zh: "我想換一件大一號的", topic: "shopping", level_cefr: "B1", context: "換貨" },
  { id: 546, zh: "這個我要送人,可以包裝嗎", topic: "shopping", level_cefr: "B1", context: "禮物包裝" },
  { id: 547, zh: "你們有在做退稅嗎", topic: "shopping", level_cefr: "B1", context: "觀光退稅" },
  { id: 548, zh: "可以幫我收著嗎,我等等來拿", topic: "shopping", level_cefr: "B1", context: "寄放商品" },
  { id: 549, zh: "我之前買的壞了", topic: "shopping", level_cefr: "B1", context: "退換貨" },
  { id: 550, zh: "收據不見了還可以退嗎", topic: "shopping", level_cefr: "B1", context: "退貨問題" },
  { id: 551, zh: "這個有保固嗎", topic: "shopping", level_cefr: "B1", context: "售後服務" },
  { id: 552, zh: "我好像被多收錢了", topic: "shopping", level_cefr: "B1", context: "帳單爭議" },
  { id: 553, zh: "我不需要袋子", topic: "shopping", level_cefr: "B1", context: "拒絕塑膠袋" },
  { id: 554, zh: "我想改用另一張卡付", topic: "shopping", level_cefr: "B1", context: "換付款" },
  { id: 555, zh: "等一下,我再想想", topic: "shopping", level_cefr: "B1", context: "暫緩購買" },

  // ── B2 消費生活（15 題） ──
  // 餐廳點餐 (B2, 8 題)
  { id: 556, zh: "這道菜用的是什麼食材", topic: "shopping", level_cefr: "B2", context: "深度問菜" },
  { id: 557, zh: "這個份量夠兩個人吃嗎", topic: "shopping", level_cefr: "B2", context: "判斷份量" },
  { id: 558, zh: "我比較偏好清淡的口味", topic: "shopping", level_cefr: "B2", context: "表達偏好" },
  { id: 559, zh: "這瓶酒你們怎麼搭配推薦", topic: "shopping", level_cefr: "B2", context: "餐酒搭配" },
  { id: 560, zh: "味道有點跟我想的不太一樣", topic: "shopping", level_cefr: "B2", context: "微妙抱怨" },
  { id: 561, zh: "餐點品質跟價錢不太相符", topic: "shopping", level_cefr: "B2", context: "抱怨 CP 值" },
  { id: 562, zh: "這家餐廳的氣氛很舒服", topic: "shopping", level_cefr: "B2", context: "讚美氛圍" },
  { id: 563, zh: "我覺得這家被過譽了", topic: "shopping", level_cefr: "B2", context: "評價" },

  // 購物/收銀台 (B2, 7 題)
  { id: 564, zh: "這個價格有點超出我的預算", topic: "shopping", level_cefr: "B2", context: "預算考量" },
  { id: 565, zh: "我想比較一下再決定", topic: "shopping", level_cefr: "B2", context: "謹慎購買" },
  { id: 566, zh: "這個跟網路上的規格不一樣", topic: "shopping", level_cefr: "B2", context: "質疑商品" },
  { id: 567, zh: "我希望有更好的解決方案", topic: "shopping", level_cefr: "B2", context: "客訴" },
  { id: 568, zh: "我要找你們主管", topic: "shopping", level_cefr: "B2", context: "升級投訴" },
  { id: 569, zh: "這樣的服務讓我很失望", topic: "shopping", level_cefr: "B2", context: "申訴" },
  { id: 570, zh: "能不能有些誠意的補償", topic: "shopping", level_cefr: "B2", context: "要求補償" },
];

export const TOPICS = {
  daily:    { name: "日常生活", emoji: "☕" },
  shopping: { name: "消費生活", emoji: "🍽️" },
  work:     { name: "工作職場", emoji: "💼" },
  emotion:  { name: "情緒表達", emoji: "💭" },
  travel:   { name: "旅遊",    emoji: "✈️" },
  opinion:  { name: "意見表達", emoji: "🎯" },
};

// CEFR 級別定義
export const LEVELS = {
  A2: {
    name: "初級",
    subtitle: "日常生存英文",
    desc: "簡單句型,應付基本溝通",
    color: "emerald",
    emoji: "🌱",
  },
  B1: {
    name: "中級",
    subtitle: "流暢日常表達",
    desc: "能完整表達想法和感受",
    color: "amber",
    emoji: "🔥",
  },
  B2: {
    name: "進階",
    subtitle: "複雜情境溝通",
    desc: "處理抽象、微妙的表達",
    color: "violet",
    emoji: "💎",
  },
};
